### ISSUE TITLE
bulk-decaffeinate view-errors uploads code?

### ISSUE THREAD

**Issue by andrewaustin** [alangpierce/bulk-decaffeinate#20]
It wasn't clear from running the readme but it looks like running view-errors sends a GET request with your failed code to the main decaffeinate project's repl. I mistakenly thought it was local repl. 

This seems problematic for commercial code.

**Comment by alangpierce** [comment]
The code is actually never sent to the server because it's in the hash fragment of the URL. You can verify in the Chrome dev tools that the GET request is only to `http://decaffeinate-project.org/repl/`, no query params. Really, the repl is just a static site and all of the actual work is done client-side. Also, it's hosted on surge.sh, which I think (but don't know for sure) doesn't give you access to the request logs anyway (although I'm sure surge.sh keeps its own request logs). Also, if you want, you can read the [source code](https://github.com/decaffeinate/decaffeinate-project.org) to confirm that the JS isn't doing anything sneaky like sending your code up.

But I definitely understand the worry and the surprise. Since it's actually not a problem, I'm thinking that I'll just update the `view-errors` part of the README to explain that it opens a decaffeinate-project.org URL, but the code is in the hash fragment, so it's not sent to the server. Does that seem reasonable to you?

(Also, I have thought about hosting a local server for the repl, but it would be more work. The main cool feature you could get is the ability to save your changes back to the filesystem after tweaking the code to make decaffeinate work.)

**Comment by andrewaustin** [comment]
Oops, you're right. I should have realized that. Thanks for the quick response.

**Comment by alangpierce** [comment]
Ok, updated, thanks for the report!
