### ISSUE TITLE
git commit hooks prevent commits in some cases

### ISSUE THREAD

**Issue by eventualbuddha** [alangpierce/bulk-decaffeinate#44]
Simple way to fix is to commit using `--no-verify`. I think it might be better to use [nodegit](http://www.nodegit.org) (uses libgit2), though.

**Comment by alangpierce** [comment]
Sure, makes sense. I think for now I'll just add `--no-verify` for now since it's easy. Out of curiosity, what commit hook failures were you hitting? Is it the type of thing that could potentially be avoided if you had more control over the commit message?

Agreed that a programmatic interface to git would be better than shell commands, although it looks to me like nodegit is really low-level and requires a lot of boilerplate, e.g. in the [add-and-commit.js example](https://github.com/nodegit/nodegit/blob/master/examples/add-and-commit.js), which still doesn't handle looking up the author/committer from the config or generating a proper timestamp. But maybe there's an alternative or maybe it isn't actually that bad.

**Comment by eventualbuddha** [comment]
I created a basic version of some of what bulk-decaffeinate does using nodegit. It is on the lower-level side for sure, but once you get used to it (and write a helper function or two) it's not that bad. You can get the default author/committer info using [`Repository#defaultSignature`](http://www.nodegit.org/api/repository/#defaultSignature), and here's what I used to make doing commits a little easier:

```js
async function commitWithChangesToIndex(repo, message, callback) {
  const signature = repo.defaultSignature();
  const index = await repo.refreshIndex();

  await callback(index);
  await index.write();
  const treeOid = await index.writeTree();
  const head = await repo.getHeadCommit();

  return await repo.createCommit(
    'HEAD',
    signature,
    signature,
    message,
    treeOid,
    head ? [head] : null
  );
}
```

And here's an example of using it:

```js
async function renameCoffeeScriptToJavaScript(repo, coffeePath, jsPath) {
  return await commitWithChangesToIndex(
    repo,
    'Rename CoffeeScript file to `.js` to prepare for conversion.',
    index => index.addByPath(jsPath).then(() => index.removeByPath(coffeePath))
  );
}
```

**Comment by alangpierce** [comment]
Cool, thanks for the advice and examples. I'm hoping to write a "land" command that makes the set of commits into a merge commit after it has gone through code review (and also optionally changes the commit messages to make Phabricator happy), and I imagine changing things to use nodegit may make that easier.

By the way, do you think you'll be able to get to the decaffeinate (and decaffeinate-parser and coffee-lex) PRs at some point? :-) There are some other people using decaffeinate now at my work and it's a bit hard to send them a build with all patches applied in all projects. You still prefer to take a look at everything, right?

**Comment by eventualbuddha** [comment]
> You still prefer to take a look at everything, right?

Since I just merged the 5 pending PRs without needing to make any adjustments I'd say go ahead and merge them after a sufficient delay (~hours).

> I'm hoping to write a "land" command that makes the set of commits into a merge commit

Yeah, I've been wanting something similar. You probably need to keep a commit of just renames but you could have a single commit for all the conversion and fixes or split those into their own commits too.

**Comment by alangpierce** [comment]
Cool, sounds good. I'll try not to break things too badly. :-)

And yeah, agreed that the only important thing is that the renames happen in their own commit, but since that requires a workflow for landing multiple commits as a merge commit, I figure it's nice to split it up a bit further. That way, if a bug does come up, it's easier to figure out if it was caused by decaffeinate or a follow-up automated transform or a manual change. I just added a `land` command that detects the set of commits and makes a merge commit, although the Phabricator support is probably the most useful part of that command.
